### ISSUE TITLE
计划功能

### ISSUE THREAD

**Issue by a7650** [a7650/h5-editor#1]
### 计划功能

- [x] 组件拖拽，旋转，缩放

- [x] 添加组件基础框架实现

- [x] 组件control，组件control基础框架实现

- [x] 组件父类Widget实现，增加基础mixins，基础config，组件锁定，隐藏，删除，init等基础功能

- [x] 图片类ImageWidget

- [x] 添加图片自动适配大小

- [x] 背景类BackgroundWidget，有纯色背景和图片背景，纯色背景不可拖动，旋转，缩放，图片背景无限制

- [x] 文本类TextWidget

- [x] 增加文本编辑，文本control：文本样式，边框，背景自定义编辑

- [x] 矩形类RectWidget，矩形绘制类DrawRectWidget

- [x] 增加矩形绘制，矩形control：矩形边框，背景，弧度自定义编辑

- [x] 右键菜单，Widget类增加基础菜单命令，组件自定菜单命令，基础菜单命令配置，command执行机制，invokeFunctionMap配置

- [x] 图层面板

- [x] 图层管理，图层item重命名，图层item添加常用命令（删除，锁定/解锁，隐藏）

- [x] 图层item拖拽调整层级

- [x] 图层面板推拽调整位置

- [x] 组件复制粘贴

- [x] ctrl + 拖动 快速复制

- [ ] 组件组合，取消组合

- [x] 快捷键复制粘贴删除

- [x] 参考线、标尺

- [x] 拖拽过程实时参考线，自动吸附

- [ ] 锁定纵横比

- [ ] 图片处理

- [x] 操作撤销

- [x] 更改画布size

- [ ] 清空画布

- [x] ctrl选中多个组件

- [x] 多组件移动，对齐

- [x] 编辑器数据备份

- [x] 生成html文件

- [x] 生成图片

- [ ] 独立打包成一个可以调用的模块

**Comment by labbomb** [comment]
想和你一起完善这个项目，能否留个联系方式

**Comment by a7650** [comment]
> 想和你一起完善这个项目，能否留个联系方式

我计划年后对这个项目用Vue3重构，并且会加上一些新功能，Vue2的暂不维护了。

**Comment by labbomb** [comment]
> 联系

想到一块了，我就是打算用vue3制作的

**Comment by labbomb** [comment]
> > 想和你一起完善这个项目，能否留个联系方式
> 
> 我计划年后对这个项目用Vue3重构，并且会加上一些新功能，Vue2的暂不维护了。

想到一块了，就是打算用vue3搭建，我还没和你说这个想法呢，哈哈哈

**Comment by QinHui-A** [comment]
👍

**Comment by jooyin** [comment]
请问现在的版本能生成图片吗？如果想要生成图片，实现思路是怎么样的呢？

**Comment by a7650** [comment]
> 请问现在的版本能生成图片吗？如果想要生成图片，实现思路是怎么样的呢？

可以生成图片，但是我把它注释掉了，你把代码拉到你本地，然后找到`views/posterEditor/extendSideBar/index.vue`这个文件，里面的第83行，把注释去掉就行了。
