### ISSUE TITLE
为啥画布的宽度不让编辑呢？

### ISSUE THREAD

**Issue by zhongpingyong** [a7650/h5-editor#6]
如果可以编辑画布的宽度是不是就能支持PC端页面了？

**Comment by a7650** [comment]
> 如果可以编辑画布的宽度是不是就能支持PC端页面了？

因为当初只是想做移动端的，移动端编辑宽度是没意义的，所以就不让编辑宽度了。
如果要编辑宽度的话，还需要开发，比如支持视图横向滚动，滚动时要校准标尺和参考线的位置，还有自动吸附对齐功能也要适配，类似于现在的竖向滚动。
因为现在的系统是基于绝对定位的，这样的编辑方式在移动端没什么大问题，但是在pc端体验会很不好，所以要是想做pc端的页面编辑器的话，我比较倾向基于flex或grid这样自适应的方式，和现在的编辑器是完全不同的逻辑。
所以理论上目前的编辑器是可以做到编辑宽度的功能的，但是我觉得PC端的体验不好  所以就没做。

**Comment by zhongpingyong** [comment]
> > 如果可以编辑画布的宽度是不是就能支持PC端页面了？
> 
> 因为当初只是想做移动端的，移动端编辑宽度是没意义的，所以就不让编辑宽度了。
> 如果要编辑宽度的话，还需要开发，比如支持视图横向滚动，滚动时要校准标尺和参考线的位置，还有自动吸附对齐功能也要适配，类似于现在的竖向滚动。
> 因为现在的系统是基于绝对定位的，这样的编辑方式在移动端没什么大问题，但是在pc端体验会很不好，所以要是想做pc端的页面编辑器的话，我比较倾向基于flex或grid这样自适应的方式，和现在的编辑器是完全不同的逻辑。
> 所以理论上目前的编辑器是可以做到编辑宽度的功能的，但是我觉得PC端的体验不好 所以就没做。

**Comment by zhongpingyong** [comment]
> > 如果可以编辑画布的宽度是不是就能支持PC端页面了？
> 
> 因为当初只是想做移动端的，移动端编辑宽度是没意义的，所以就不让编辑宽度了。
> 如果要编辑宽度的话，还需要开发，比如支持视图横向滚动，滚动时要校准标尺和参考线的位置，还有自动吸附对齐功能也要适配，类似于现在的竖向滚动。
> 因为现在的系统是基于绝对定位的，这样的编辑方式在移动端没什么大问题，但是在pc端体验会很不好，所以要是想做pc端的页面编辑器的话，我比较倾向基于flex或grid这样自适应的方式，和现在的编辑器是完全不同的逻辑。
> 所以理论上目前的编辑器是可以做到编辑宽度的功能的，但是我觉得PC端的体验不好 所以就没做。

原来是这样，大佬厉害了
