### ISSUE TITLE
导出html可以样式单独抽出css文件

### ISSUE THREAD

**Issue by cc-qq-gg** [a7650/h5-editor#7]

**Comment by a7650** [comment]
当然可以，现在的导出只是个demo，还有很多优化没做，所以你会看到导出的体积较大，因为现在的样式大部分都是内联样式，所以有很多重复的，其实可以在导出时对这些样式进行分析，将重复样式的写在在css里面，然后多个dom都引用类名就可以了。
只是最近我太忙了，我还有许多其他要紧的事情要做，这个就暂时没有维护了，我估计年后才有时间。
如果你有想法的话，你可以fork一份去修改。
